# Generated by Django 5.0.1 on 2024-05-24 04:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arte',
            name='mensaje',
            field=models.CharField(default='', max_length=150),
        ),
    ]
